### ISSUE TITLE
feat: Social preview via OpenGraph

### ISSUE THREAD

**Issue by ligi** [Etherna/etherna-website#81]
Would like to use the etherna link more to share the videos - but not having a social preview makes it less appealing.
It would be great if etherna could support e.g. og:image

**Comment by mattiaz9** [comment]
Thanks @ligi. 
We already looked into it, but since the pages are not server-side rendered all metadata is download after the page is loaded, resulting in a "empty" OG information.

BTW this is our marketing website. You can find the dapp repository here: https://github.com/Etherna/etherna-dapp. 
And if you find any other issues you can open them at this link: https://etherna.atlassian.net/jira/software/c/projects/EDD/issues
